exploit-urllib2.py funcionou com sucesso! possível execução de comando remoto.
